import type { Metadata } from "next";
import type { Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Use explicit 100dvh so the app always has a bounded height for the single scroll container */}
        <div className="h-[100dvh] bg-slate-50 flex flex-col">
          <header className="sticky top-0 z-40 flex-shrink-0">
            <Navigation />
          </header>
          {/* ONLY vertical scroll area for the entire app */}
          <main
            id="app-main-scroll"
            className="flex-1 min-h-0 overflow-y-scroll"
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}